name: faker
version: 0.0.5
description: A library for generating fake data
homepage: https://github.com/drager/faker
author: Jesper Håkansson <jesper@jesperh.se>
# flutter:
#     sdk: flutter
dev_dependencies:
  # guinness: '>=0.1.17 <0.2.0'
  # unittest: '>=0.11.0 <0.12.0'
  # flutter_test:
  #     sdk: flutter    
